name: Build macOS Executable

on: 
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch. Adjust if you use a different branch.

jobs:
  build:
    runs-on: macos-latest  # Run the job on the latest macOS runner provided by GitHub.

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version you need for your project.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Install PyInstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install other dependencies if requirements.txt exists.

    - name: Build Executable
      run: pyinstaller --onefile main_gui.py  # Replace 'your_script_name.py' with the name of your main Python script.

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macOS-executable
        path: dist/main_gui  # Replace 'your_script_name' with the name of your output file from PyInstaller.

